# Generated by Django 5.2.8 on 2026-07-15 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_path', models.CharField(choices=[('individual', 'Individual'), ('hospital', 'Hospital')], max_length=20)),
                ('patient_name', models.CharField(max_length=150)),
                ('patient_contact', models.CharField(max_length=20)),
                ('blood_group', models.CharField(choices=[('O-', 'O-'), ('O+', 'O+'), ('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('B+', 'B+'), ('AB-', 'AB-'), ('AB+', 'AB+')], max_length=3)),
                ('units_required', models.PositiveIntegerField()),
                ('units_remaining', models.PositiveIntegerField(editable=False)),
                ('hospital_name_freetext', models.CharField(blank=True, help_text='Used only for Path A, where the patient types the hospital name manually.', max_length=200)),
                ('ward_location', models.CharField(blank=True, max_length=150)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('urgency_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('fulfilled', 'Fulfilled'), ('removed', 'Removed')], default='active', max_length=20)),
                ('medical_notes_structured', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by_hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_requests', to='hospitals.hospital')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
