# Generated by Django 5.2.8 on 2026-07-15 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('broadcast', 'Broadcast'), ('accepted', 'Accepted'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('closed', 'Closed — Not Chosen')], default='broadcast', max_length=20)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('donor_confirmed', models.BooleanField(default=False)),
                ('patient_confirmed', models.BooleanField(default=False)),
                ('hospital_confirmed', models.BooleanField(default=False)),
                ('units_donated', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='donors.donor')),
                ('patient_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='patients.patientrequest')),
            ],
            options={
                'ordering': ['distance_km', 'created_at'],
                'unique_together': {('patient_request', 'donor')},
            },
        ),
    ]
