# Generated by Django 5.2.8 on 2026-07-15 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('O-', 'O-'), ('O+', 'O+'), ('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('B+', 'B+'), ('AB-', 'AB-'), ('AB+', 'AB+')], max_length=3)),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('travel_radius_km', models.PositiveIntegerField(default=15)),
                ('age', models.PositiveIntegerField()),
                ('weight_kg', models.FloatField()),
                ('has_recent_tattoo_or_piercing', models.BooleanField(default=False)),
                ('has_recent_major_surgery', models.BooleanField(default=False)),
                ('on_blood_thinners', models.BooleanField(default=False)),
                ('hiv_positive', models.BooleanField(default=False)),
                ('hepatitis_b_or_c', models.BooleanField(default=False)),
                ('has_chronic_illness', models.BooleanField(default=False)),
                ('recent_malaria_endemic_travel', models.BooleanField(default=False)),
                ('is_pregnant_or_recent_childbirth', models.BooleanField(default=False)),
                ('cnic_image', models.ImageField(blank=True, null=True, upload_to='cnic_uploads/donors/')),
                ('is_cnic_verified', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('is_suspended', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('eligible', 'Eligible'), ('disqualified', 'Disqualified'), ('cooling_down', 'Cooling Down')], default='eligible', max_length=20)),
                ('next_eligible_date', models.DateField(blank=True, null=True)),
                ('donation_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
